### ISSUE TITLE
temporary file write error

### ISSUE THREAD

**Issue by erikkurtu** [stevedem/splitpdfs#2]
Thanks for this. I'm trying to use it and the function is producing a 500 error at:

```
with open(temp_pdf_fn, "wb") as outputStream:
    output.write(outputStream)
```

Do I need any additional setup to temporarily save the pdf? Like a connection to a storage account?

Only difference in my situation is that I'm sending an email attachment so the request body to the function is:

```
                              "body": {
                                  "fileContent": "@items('For_each')['contentBytes']",
                                  "fileName": "@items('For_each')['name']"
                              }
```

And the function reads the file content as:
`file_content = req_body['fileContent']`

**Comment by erikkurtu** [comment]
FYI, I had to add /tmp/ to a couple lines to get to a writable directory in the function:

```
            with open('/tmp/' + temp_pdf_fn, 'wb') as outputStream:
                output.write(outputStream)
            with open('/tmp/' + temp_pdf_fn, 'rb') as temp_pdf_file:
                file_data = base64.b64encode(temp_pdf_file.read()).decode()
                ind_pdf = {
                    'fileName': temp_pdf_fn,
                    'fileContent': file_data
                }
```

Works well now. Thanks!

**Comment by Kolt45** [comment]
Updating line 16 to `file_content = req_body['fileContent']` as you mentioned in your first comment and adding the /tmp/ paths from your second comment also fixed my implementation. Note that I am using Power Automate instead of Logic Apps as described in the Readme.  Not familiar with Logic Apps but some of the information I have gathered from Azure Functions conference talks has shown that they are definitely related to some extent (visual scripting and/or low code products from Microsoft).

**Comment by stevedem** [comment]
The way that Function Apps handles local storage changed after I published the first version of this Function App. I've recently updated the code to leverage the `'HOME'` environment variable. 

```python
HOME_LOCAL_DIR = os.environ['HOME']
logging.info(f"HOME_DATA_DIR: {HOME_LOCAL_DIR}")
```

Which I then use when referencing a local file.

```python
temp_pdf_fn = pdf_prefix_file_name + str(i + 1) + '_' + dt + str(".pdf")
temp_pdf_fp = os.path.join(HOME_LOCAL_DIR, temp_pdf_fn)
```
